create table url
(
    url_id       bigint generated by default as identity primary key,
    long_url     text      not null unique,
    created_at   TIMESTAMP not null,
    expires_date TIMESTAMP not null
);